/***
 Fichier fabriqué automatiquement
 NE PAS MODIFIER À LA MAIN
 Cf. /Users/philippeperret/Sites/AlwaysData/Icare_2020/_lib/_pages_/admin/tools/updater_data.rb:37
***/const DATA_OPERATIONS = {
'add_actualite': {description: null, aide: null, for: "all", select_value: {"values":[["SIMPLEMESS","Simple message"],["FIRSTPAIE","Premier paiement"],["SIGNUP","Nouvelle inscription"],["SENDWORK","Envoi de travail"],["REALICARIEN","Vrai icarien/icarienne"],["STARTMOD","Démarrage de module"],["QDDDEPOT","Dépôt sur le Quai des docs"],["COMMENTS","Envoi des commentaires sur documents"],["CHGETAPE","Changement d’étape"],["ENDMODULE","Fin de module"]],"default":"SIMPLEMESS","message":"Type de l’actualité"}, cb_value: null, long_value: "Message d'actualité à attribuer à l'icarien sélectionné (ou à Phil si aucun). Le message sera évalué, donc on peut utiliser des `\#{icarien.pseudo}` à l'intérieur (code ruby évalué comme dans un String normal).", medium_value: null, short_value: "Date JJ/MM (si différente d’aujourd’hui)", required:["long_value"]},
'arret_module': {description: null, aide: null, for: "actif", select_value: null, cb_value: null, long_value: "Si un texte (en HTML) est écrit ci-dessous, il sera considéré comme le supplément d’un mail à envoyer à l’icarien du module l’informant de l’arrêt/la fin de son module. Dans le cas contraire, le module sera simplement arrêté.", medium_value: null, short_value: null, required:["icarien"]},
'change_module': {description: null, aide: null, for: "actif", select_value: null, cb_value: null, long_value: null, medium_value: "Numéro de la nouvelle étape dans le nouveau module (on peut l’obtenir avec l’outil Burea > Édition des étapes)", short_value: "ID du nouveau module absolu d’apprentissage (on peut le trouver avec l’outils Bureau > Édition des étapes, c’est le nombre entre parenthèses après le nom du module)", required:["short_value","icarien","medium"]},
'code_sur_table': {description: null, aide: null, for: "all", select_value: null, cb_value: null, long_value: "Code à exécuter <strong>sur chaque icarien de la table</strong>, sur la table OFFLINE puisse que vous êtes OFFLINE.<br><br><code>User.each do |cu|<br>&nbsp;&nbsp;cu.&lt;what&gt;</code>", medium_value: null, short_value: null, required:["long_value"]},
'destroy_user': {description: null, aide: null, for: "all", select_value: null, cb_value: null, long_value: null, medium_value: null, short_value: "ID de l’icarien choisi (pour confirmation)", required:["short_value","icarien"]},
'etape_change': {description: null, aide: null, for: "actif", select_value: null, cb_value: null, long_value: null, medium_value: null, short_value: "Numéro de l’étape", required:["short_value","icarien"]},
'free_days': {description: null, aide: null, for: "actif", select_value: null, cb_value: {"checked":true,"message":"Informer l’icarien·ne par mail (avec le message ci-dessus s'il est défini)."}, long_value: "Raison éventuelle du don de jours gratuits (format ERB).", medium_value: null, short_value: "Nombre de jours gratuits", required:["short_value","icarien"]},
'inject_document': {description: null, aide: null, for: "actif", select_value: null, cb_value: null, long_value: null, medium_value: "Nom du fichier", short_value: null, required:["medium_value","icarien"]},
'marquer_detruit': {description: "Cet outil permet de marquer un icarien comme détruit, mais sans le détruire. Toutes ses productions seront simplement marquées comme “anonyme”.", aide: null, for: "all", select_value: null, cb_value: null, long_value: null, medium_value: null, short_value: "ID de l’icarien, pour confirmation", required:["short_value"]},
'move_document': {description: null, aide: null, for: ["actif","inactif","pause"], select_value: null, cb_value: null, long_value: null, medium_value: "ID de l’icetape de destination", short_value: "ID du document", required:["short_value","medium_value","icarien"]},
'nettoyage_site': {description: null, aide: null, for: "all", select_value: null, cb_value: null, long_value: null, medium_value: null, short_value: null, required:[]},
'pause_module': {description: null, aide: null, for: "actif", select_value: null, cb_value: null, long_value: null, medium_value: null, short_value: "X pour ne pas envoyer l'email", required:["icarien"]},
'restart_module': {description: null, aide: null, for: "pause", select_value: null, cb_value: null, long_value: null, medium_value: null, short_value: null, required:["icarien"]},
'temoignage': {description: null, aide: null, for: "all", select_value: null, cb_value: null, long_value: "Code HTML du témoignage à ajouter", medium_value: null, short_value: "ID du témoignage si c’est une modification", required:["long_value","icarien"]},
'titre_projet': {description: null, aide: null, for: ["actif","inactif","pause"], select_value: null, cb_value: null, long_value: null, medium_value: "Titre du projet (ou rien pour le supprimer)", short_value: "ID du IcModule si ça n’est pas le courant", required:["icarien"]},
'travail_propre': {description: null, aide: null, for: "actif", select_value: null, cb_value: null, long_value: "Description du travail propre (format ERB).<br>Laisser vide et cliquez sur “Exécuter” pour charger le travail qui peut déjà exister.", medium_value: null, short_value: null, required:["long_value","icarien"]}
};